### PR TITLE
Added Reactions

### PR DESCRIPTION
**Pull request by ibortolazzi**
The new feature for bot reactions is now included with an example of random reaction and big reactions.

### CODE REVIEW

**Comment by cvzi** [comment]
There is something missing, you don't actually choose an emoji from `reactions_`

**Comment by ibortolazzi** [comment]
Sorry, when I removed the debug code it seems I took that out too. Now it should be fixed.

**Comment by cvzi** [comment]
Thanks!

**Comment by cvzi** [comment]
Someone asked me if I could license this repository under MIT license, because for some reason (that I don't really understand) they can't use the current license (which is CC0 1.0) in their country.

Personally I don't care about the license, so I would just add "MIT" and also "GPL v3 or later" to cover all bases. 
Since the repository contains your changes as well, I want to ask you if you agree to license under "MIT" and/or "GPL v3 or later" license?

If you agree, I would just create two new branches and add those licenses to the branches. The main branch would stay as it is.

Sorry to bother you about this.

**Comment by ibortolazzi** [comment]
Hi!
First of all, thanks for asking! The code base is yours and I just contributed, but it is a nice and appreciated gesture and does not bother me at all.
I have no problem in changing to MIT or GPL.

**Pull request merged**
